version: '3.7'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    container_name: elasticsearch
    volumes:
     - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: youpassword
    networks:
     - elk

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.5.4
    container_name: filebeat
    command: bash -c "sleep 30 && filebeat -e -strict.perms=false"
    #volumnes mount depend on you OS ( Windows or Linux )
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./data:/var/log/test
      - ./var/log:/var/log
    networks:
      - elk
    links:
       - elasticsearch
       - kibana
    depends_on:
       - elasticsearch
       - kibana

  elastalert:
      links:
          - elasticsearch
      image: bitsensor/elastalert
      container_name: elastalert
      environment:
          ELASTALERT_USER: "elastalert"
          ELASTALERT_PWD: "changeme"
          ELASTICSEARCH_HOST: "elasticsearch"
          ELASTICSEARCH_PORT: "9200"
      volumes:
          - ./elastalert/config/elastalert.yaml:/opt/elastalert/config.yaml:ro
          - ./elastalert/config/config.json:/opt/elastalert-server/config/config.json:ro
          - ./elastalert/rules/:/opt/elastalert/rules/
          - ./elastalert/rule_templates/:/opt/elastalert/rule_templates/
      ports:
        - 3030:3030
      #logging:
      #  driver: syslog
      #  options:
      #    syslog-address: "tcp://:5000"
      networks:
          - elk
      restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.4
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: youpassword
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - elasticsearch
    links:
      - elasticsearch

networks:
  elk:
    driver: bridge
